small improvements, and a couple new scripts

diff --git a/scripts/.myScripts/keydprofile b/scripts/.myScripts/keydprofile
--- a/scripts/.myScripts/keydprofile
+++ b/scripts/.myScripts/keydprofile
@@ -5,15 +5,18 @@ infoColor="\033[32m"
 errorColor="\033[31m"
 resetSeq="\033[0m"
 
+# we choose a target device, or see auxiliary options
 DEVICE=$(gum choose --header "choose a device:" $(basename -a /etc/keyd/profiles/*) "auxiliary options...")
-[ -z "$DEVICE" ] && { echo "aborting..."; exit 0; }
+[ -z "$DEVICE" ] && { echo "aborting..."; exit 1; }
 
+# some auxiliary options are shown
 if [ "$DEVICE" = "auxiliary options..." ]; then
   # the extra options are shown
   DEVICE=$(gum choose --header "choose an option:" "print current configs" "toggle keyd")
-  [ -z "$DEVICE" ] && { echo "aborting..."; exit 0; }
+  [ -z "$DEVICE" ] && { echo "aborting..."; exit 1; }
 fi
 
+# option 1: we format and print the current configs
 if [ "$DEVICE" = "print current configs" ]; then
   # we check if keyd is active
   if ! systemctl is-active --quiet keyd; then
@@ -31,6 +34,7 @@ if [ "$DEVICE" = "print current configs" ]; then
   exit 0
 fi
 
+# option 2: we toggle keyd
 if [ "$DEVICE" = "toggle keyd" ]; then
   # keyd is started/stopped, according to its current state
   if systemctl is-active --quiet keyd; then
@@ -43,37 +47,46 @@ if [ "$DEVICE" = "toggle keyd" ]; then
   exit 0
 fi
 
+# option 3: we actually chose a device; we now choose a profile (an additional disable option is included)
 PROFILE=$(gum choose --header "choose a profile:" $(basename -a /etc/keyd/profiles/$DEVICE/* | grep -v layers) "disable $DEVICE")
-[ -z "$PROFILE" ] && { echo "aborting..."; exit 0; }
+[ -z "$PROFILE" ] && { echo "aborting..."; exit 1; }
 
+
+# option 3.1: we disable the device
 if [ "$PROFILE" = "disable $DEVICE" ]; then
   # the config for the device is deleted
   sudo rm /etc/keyd/$DEVICE.conf
   echo -e "${targetColor}$DEVICE${resetSeq} disabled!"
+# option 3.2: we ask whether to apply this profile to all devices
 else
-  SETALLDEVICES=$(gum choose --header "change all devices to $PROFILE?" "yes" "no")
-  [ -z "$SETALLDEVICES" ] && { echo "aborting..."; exit 0; }
+  SET_ALL_DEVICES=$(gum choose --header "change all devices to $PROFILE?" "yes" "no")
+  [ -z "$SET_ALL_DEVICES" ] && { echo "aborting..."; exit 1; }
 
   # the config for the device is updated
   sudo ln -sf profiles/$DEVICE/$PROFILE /etc/keyd/$DEVICE.conf
   echo -e "${targetColor}$DEVICE${resetSeq} profile set to: ${infoColor}$PROFILE${resetSeq}"
 fi
 
-if [ "$SETALLDEVICES" = "yes" ]; then
-  # the config for all remaining devices is updated
-  for AUXDEVICE in $(basename -a /etc/keyd/profiles/* | grep -v $DEVICE); do
-    if [[ -f "/etc/keyd/profiles/$AUXDEVICE/$PROFILE" ]]; then
-      sudo ln -sf profiles/$AUXDEVICE/$PROFILE /etc/keyd/$AUXDEVICE.conf
-      echo -e "${targetColor}$AUXDEVICE${resetSeq} profile set to: ${infoColor}$PROFILE${resetSeq}"
+# option 3.2.1: we apply this profile to all devices
+if [ "$SET_ALL_DEVICES" = "yes" ]; then
+  for AUX_DEVICE in $(basename -a /etc/keyd/profiles/* | grep -v $DEVICE); do
+    # if the profile exists, we set it
+    if [[ -f "/etc/keyd/profiles/$AUX_DEVICE/$PROFILE" ]]; then
+      sudo ln -sf profiles/$AUX_DEVICE/$PROFILE /etc/keyd/$AUX_DEVICE.conf
+      echo -e "${targetColor}$AUX_DEVICE${resetSeq} profile set to: ${infoColor}$PROFILE${resetSeq}"
+    # else, we warn the user
     else
-      echo -e "${errorColor}$PROFILE${resetSeq} profile for ${errorColor}$AUXDEVICE${resetSeq} not found!"
+      echo -e "${errorColor}$PROFILE${resetSeq} profile for ${errorColor}$AUX_DEVICE${resetSeq} not found!"
     fi
   done
 fi
 
-# if keyd is active, it gets reloaded. Otherwise the service is restarted
+# final step: if keyd is active, it gets reloaded. Otherwise the service is started
 if systemctl is-active --quiet keyd; then
   sudo keyd reload
 else
   sudo systemctl start keyd
 fi
+
+# done!
+exit 0
