feat(keydprofile): I can now debug with `keyd listen` and `keyd monitor`
+ minor bugfixes

diff --git a/home/david/software/config/myScripts/keydprofile b/home/david/software/config/myScripts/keydprofile
--- a/home/david/software/config/myScripts/keydprofile
+++ b/home/david/software/config/myScripts/keydprofile
@@ -34,17 +34,24 @@ EOF
 
 # main() implements a single keydprofile transaction
 main(){
+  # init of empty variables
+  DEVICE=
+  AUX_OPTION=
+  DEBUG_OPTION=
+  PROFILE=
+  SET_ALL_DEVICES=
+
   # we choose a target device, or see auxiliary options; we exit if no choice is made
   DEVICE=$(gum choose --header "choose a device:" $(basename -a /etc/keyd/profiles/*) "auxiliary options...") || exit 1
 
   # option 1: some auxiliary options are shown
   if [ "$DEVICE" = "auxiliary options..." ]; then
     # the extra options are shown
-    DEVICE=$(gum choose --header "choose an option:" "print current configs" "toggle keyd") || exit 1
+    AUX_OPTION=$(gum choose --header "choose an option:" "print current configs" "toggle keyd" "debug options...") || exit 1
   fi
 
   # option 1.1: we format and print the current configs
-  if [ "$DEVICE" = "print current configs" ]; then
+  if [ "$AUX_OPTION" = "print current configs" ]; then
     # we check if keyd is active
     if ! systemctl is-active --quiet keyd; then
       echo -e "\033[33mkeyd is not active!${resetSeq}"
@@ -62,7 +69,7 @@ main(){
   fi
 
   # option 1.2: we toggle keyd
-  if [ "$DEVICE" = "toggle keyd" ]; then
+  if [ "$AUX_OPTION" = "toggle keyd" ]; then
     # keyd is started/stopped, according to its current state
     if systemctl is-active --quiet keyd; then
       sudo systemctl stop keyd
@@ -74,6 +81,24 @@ main(){
     return 0
   fi
 
+  # option 1.3: debug options
+  if [ "$AUX_OPTION" = "debug options..." ]; then
+    # the extra options are shown
+    DEBUG_OPTION=$(gum choose --header "choose an option:"  "keyd listen" "keyd monitor") || exit 1
+  fi
+
+  # option 1.3.1: keyd listen
+  if [ "$DEBUG_OPTION" = "keyd listen" ]; then
+    sudo keyd listen
+    return 0
+  fi
+
+  # option 1.3.2: keyd monitor
+  if [ "$DEBUG_OPTION" = "keyd monitor" ]; then
+    sudo keyd monitor
+    return 0
+  fi
+
   # option 2: we actually chose a device; we now choose a profile (an additional disable option is included)
   PROFILE=$(gum choose --header "choose a profile:" $(basename -a /etc/keyd/profiles/$DEVICE/* | grep -v layers) "disable $DEVICE") || exit 1
 
@@ -82,27 +107,24 @@ main(){
     # the config for the device is deleted
     sudo rm /etc/keyd/$DEVICE.conf
     echo -e "${targetColor}$DEVICE${resetSeq} disabled!"
-  # option 2.2: some profile was chosen; we apply it, and we ask whether to apply it to all devices as well
-  else
-    SET_ALL_DEVICES=$(gum choose --header "change all devices to $PROFILE?" "yes" "no") || exit 1
-
-    # the config for the device is updated
+  else # option 2.2: some profile was chosen;  we apply it
     sudo ln -sf profiles/$DEVICE/$PROFILE /etc/keyd/$DEVICE.conf
     echo -e "${targetColor}$DEVICE${resetSeq} profile set to: ${infoColor}$PROFILE${resetSeq}"
-  fi
 
-  # option 2.2.1: we apply this profile to all devices
-  if [ "$SET_ALL_DEVICES" = "yes" ]; then
-    for AUX_DEVICE in $(basename -a /etc/keyd/profiles/* | grep -v $DEVICE); do
-      # if the profile exists, we set it
-      if [[ -f "/etc/keyd/profiles/$AUX_DEVICE/$PROFILE" ]]; then
-        sudo ln -sf profiles/$AUX_DEVICE/$PROFILE /etc/keyd/$AUX_DEVICE.conf
-        echo -e "${targetColor}$AUX_DEVICE${resetSeq} profile set to: ${infoColor}$PROFILE${resetSeq}"
-        # else, we warn the user
-      else
-        echo -e "${errorColor}$PROFILE${resetSeq} profile for ${errorColor}$AUX_DEVICE${resetSeq} not found!"
-      fi
-    done
+    # option 2.2.1: we ask whether to apply it to all devices as well, and we apply all necessary profiles
+    SET_ALL_DEVICES=$(gum choose --header "change all devices to $PROFILE?" "yes" "no") || exit 1
+    if [ "$SET_ALL_DEVICES" = "yes" ]; then
+      for AUX_DEVICE in $(basename -a /etc/keyd/profiles/* | grep -v $DEVICE); do
+        # if the profile exists, we set it
+        if [[ -f "/etc/keyd/profiles/$AUX_DEVICE/$PROFILE" ]]; then
+          sudo ln -sf profiles/$AUX_DEVICE/$PROFILE /etc/keyd/$AUX_DEVICE.conf
+          echo -e "${targetColor}$AUX_DEVICE${resetSeq} profile set to: ${infoColor}$PROFILE${resetSeq}"
+          # else, we warn the user
+        else
+          echo -e "${errorColor}$PROFILE${resetSeq} profile for ${errorColor}$AUX_DEVICE${resetSeq} not found!"
+        fi
+      done
+    fi
   fi
 
   # final step: if keyd is active, it gets reloaded. Otherwise the service is started
@@ -116,7 +138,6 @@ main(){
 }
 
 while true; do
-
   # perform a transation
   main
 
@@ -126,7 +147,6 @@ while true; do
   # in gui mode we can loop
   IFS= read -rn1 -p $'\nPress Space to continue, or any key to exit...' choice
   [[ $choice == " " ]] || break
-
 done
 
 exit 0
